version: "2"
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/.minio/data:/data
      - ./minio/.minio/config:/root/.minio
    environment:
      - "MINIO_ROOT_USER=ADMINUSER2143542"
      - "MINIO_ROOT_PASSWORD=d321c411-1a9b-460b-8259-194be048f505"
    command: server /data --console-address ":9001"
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MinioEndpoint=minio
    depends_on:
      - minio